services:
  telegram_bot_sismo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_sismo
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SITE_URL=https://localizadosvenezuela.com
